.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitclassic_coin test_bitclassic_coin
clean: FORCE
	$(MAKE) -C .. bitclassic_coin_clean test_bitclassic_coin_clean
check: FORCE
	$(MAKE) -C .. test_bitcoin_qt_check
bitclassic-coin bitclassic-coin.exe: FORCE
	 $(MAKE) -C .. bitclassic_coin
